version: '3'
services:
  web:
    build: .
    command: 'nodemon -L --inspect=0.0.0.0:5858'
    volumes:
      - '.:/code'
    ports:
      - '8080:8080'
      - '8000:8000'
      - '5858:5858'
      - '4200:4200'
      - '3000:3000'
    
