version: '3'
services:
  web:
    build: .
    command: 'nodemon -L --inspect=0.0.0.0:5858'
    volumes:
      - '.:/code'
    ports:
      - '8000:8000'
      - '5858:5858'
      - name: Build and push Docker images
      - uses: docker/build-push-action@v2.1.0

