version: "3"

openapi: 3.0.1
info:
  title: Fullstack Challenge 20200713
  description: CRUD Products
  version: '0.1'

services:
  web:
    build: .
    command: nodemon -L --inspect=0.0.0.0:5858
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "5858:5858"
